# NumPy 综合练习题（第 1-5 节）

**说明**：
- 本练习覆盖第 1-5 节**所有知识点**，按章节顺序排列
- 共 **8 大模块，60+ 题**，难度从 ⭐ 到 ⭐⭐⭐⭐
- 每题先想清楚**数学含义**，再写代码
- 卡住超过 5 分钟可以问 Claude，但**先自己尝试**
- 完成后对照答案（最后会给）

**预计完成时间**：4-6 小时（建议分两天做）

---

## 模块 0：环境准备

运行下面这个 cell 导入 NumPy。

In [1]:
import numpy as np
print(np.__version__)  # 看看你的 NumPy 版本

1.24.4


---

## 模块 1：理解 NumPy 与 List 的区别（第 1 节）⭐

考点：NumPy 重新定义了运算符的含义

### 题 1.1

已有两个 Python list：`a = [1, 2, 3]`，`b = [4, 5, 6]`。  
请分别用 **list** 和 **NumPy 数组** 计算它们的「逐元素相加」，对比输出。

In [6]:
# Python list 的加法（不是逐元素加）
a = [1, 2, 3]
b = [4, 5, 6]
print('list加法:',a+b) 

# NumPy 数组的加法（逐元素）
a_np = [1, 2, 3]
b_np = [4, 5, 6]
print('numpy 加法:', np.array(a)+np.array(b))

list加法: [1, 2, 3, 4, 5, 6]
numpy 加法: [5 7 9]


### 题 1.2

用**纯 Python 循环**实现两个 list 的逐元素相乘，再用 NumPy 一行实现，对比代码长度。

In [9]:
# 纯 Python 写法
a = [1, 2, 3, 4]
b = [10, 20, 30, 40]
c = []
for i in range(len(a)):
    c.append(a[i] * b[i])
print(c)

# NumPy 写法
result_np = np.array(a)*np.array(b)
print(result_np)

[10, 40, 90, 160]
[ 10  40  90 160]


---

## 模块 2：创建数组（第 2 节）⭐

考点：array、zeros、ones、eye、arange、linspace、随机数

### 题 2.1
创建一个一维 NumPy 数组：`[10, 20, 30, 40, 50]`

In [15]:
a = np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


### 题 2.2
创建一个 3 行 4 列的矩阵，第一行 [1,2,3,4]，第二行 [5,6,7,8]，第三行 [9,10,11,12]

In [20]:
M = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(M)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 题 2.3
创建一个 5×5 的零矩阵

In [23]:
Z = np.zeros([5,5])
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### 题 2.4
创建一个 4×4 的全 1 矩阵，且**数据类型为整数**（不要小数点）

In [25]:
O = np.ones([4,4],dtype = int)
print(O)
print(O.dtype)  # 应该是 int

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int32


### 题 2.5
创建一个 6×6 的单位矩阵 $I_6$

In [26]:
I = np.eye(6)
print(I)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### 题 2.6
用 `np.arange` 生成 `[2, 5, 8, 11, 14, 17, 20]`（提示：起点 2，步长 3）

In [32]:
x = np.arange(2,23,3)
print(x)

[ 2  5  8 11 14 17 20]


### 题 2.7
用 `np.linspace` 在 $[0, \pi]$ 上均匀取 11 个点

In [36]:
import math
x = np.linspace(0,math.pi,11)
print(x)

[0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265]


### 题 2.8
（统计模拟）用 `np.random.seed(42)` 设种子，然后从 $N(0, 1)$ 抽 10000 个样本，验证均值 $\approx 0$，方差 $\approx 1$

In [39]:
np.random.seed(42)
samples = np.random.randn(10000)
print('均值:', samples.mean())
print('方差:', samples.var())

TypeError: randn() got an unexpected keyword argument 'dtype'

### 题 2.9
从 $N(\mu=100, \sigma=15)$ 抽 1000 个样本（提示：用 `np.random.normal`，注意参数名 `loc` 和 `scale`）

In [42]:
samples = np.random.normal(100,15,1000)
print('均值:', samples.mean())  # 应该 ≈ 100
print('标准差:', samples.std())  # 应该 ≈ 15

均值: 100.28998083733488
标准差: 14.680893116210314


### 题 2.10（蒙特卡洛模拟）
用 100 万个随机点估计 $\pi$。

**思路**：在 $[-1, 1] \times [-1, 1]$ 正方形内随机撒点，落在单位圆内的比例 $\approx \pi/4$

In [45]:
np.random.seed(0)
n = 1000000000
x = np.random.uniform(-1,1,n)  # U(-1, 1) 抽 n 个
y = np.random.uniform(-1,1,n)  # 同上
inside = (x**2+y**2<1).sum()  # 落在 x²+y²<1 内的点数
pi_estimate = 4 * inside / n
print(f'π 估计值: {pi_estimate}')

KeyboardInterrupt: 

---

## 模块 3：数组的核心属性（第 3 节）⭐

考点：shape、ndim、dtype、size、形状的陷阱

### 题 3.1
对下面这个数组，输出它的 shape、ndim、dtype、size

In [50]:
A = np.array([[1.5, 2.5, 3.5],
              [4.5, 5.5, 6.5]])
print('shape:', A.shape)
print('ndim:',A.ndim )
print('dtype:', A.dtype)
print('size:', A.size)

shape: (2, 3)
ndim: 2
dtype: float64
size: 6


### 题 3.2（形状陷阱）
下面三个数组的 shape 分别是什么？**先猜，再验证**

In [51]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([[1, 2, 3, 4]])
v3 = np.array([[1], [2], [3], [4]])

# 你的猜测：
# v1.shape = ?
# v2.shape = ?
# v3.shape = ?

# 验证：
print(v1.shape, v2.shape, v3.shape)

(4,) (1, 4) (4, 1)


### 题 3.3
创建一个数组 `[1, 2, 3]`，dtype 为 `float32`（深度学习常用）

In [54]:
a = np.array([1,2,3],dtype=np.float32)
print(a)
print(a.dtype)  # 应该是 float32

[1. 2. 3.]
float32


### 题 3.4
把一个 float 数组转换为 int 数组（用 `.astype`）

In [55]:
a = np.array([1.7, 2.3, 3.9, 4.1])
b = a.astype(int)
print(b)        # 注意：转 int 是直接截断小数部分（向 0 截断）
print(b.dtype)  # int

[1 2 3 4]
int32


### 题 3.5（思考题，无需写代码）

下面这个数组的 shape 是什么？**先想，再验证**

```python
X = np.zeros((2, 3, 4))
```

提示：这是 3 维数组（张量），可以理解为 "2 个 3×4 的矩阵叠在一起"

In [56]:
X = np.zeros((2, 3, 4))
print(X.shape)
print(X.ndim)
print(X.size)  # 应该是 2×3×4 = 24

(2, 3, 4)
3
24


---

## 模块 4：基础运算（第 4 节，逐元素 vs 矩阵乘法）⭐⭐

考点：`+ - * /` 的逐元素含义、`@` 矩阵乘法、转置、求逆

### 题 4.1
给定 $\vec{a} = [1, 2, 3, 4]$，$\vec{b} = [5, 6, 7, 8]$，计算：
1. 逐元素加 $\vec{a} + \vec{b}$
2. 逐元素乘（Hadamard 积）$\vec{a} \odot \vec{b}$
3. 内积 $\vec{a} \cdot \vec{b}$

In [57]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print('逐元素加:', a+b)
print('Hadamard 积:', a*b)
print('内积:', a@b)  # 应该是 1*5+2*6+3*7+4*8 = 70

逐元素加: [ 6  8 10 12]
Hadamard 积: [ 5 12 21 32]
内积: 70


### 题 4.2（关键：`*` vs `@`）
对下面两个矩阵分别计算 `A * B` 和 `A @ B`，**说出它们的区别**

In [58]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print('A * B (Hadamard 积):')
print(a*b)

print('A @ B (矩阵乘法):')
print(a@b)

# 验证矩阵乘法：手算 (A@B)[0][0] 应该等于 1*5 + 2*7 = ?

A * B (Hadamard 积):
[ 5 12 21 32]
A @ B (矩阵乘法):
70


### 题 4.3（L2 范数）
计算向量 $\vec{x} = [3, 4]$ 的 L2 范数 $\|\vec{x}\|_2 = \sqrt{x_1^2 + x_2^2}$

**用 3 种方法**：
1. 用 `np.sqrt` 和 `np.sum`
2. 用 `np.sqrt` 和内积 `@`
3. 用 `np.linalg.norm`

In [64]:
x = np.array([3, 4])

norm_v1 = np.sqrt(np.sum(x ** 2))
norm_v2 = np.sqrt(x @ x)
norm_v3 = np.linalg.norm(x)

print(norm_v1, norm_v2, norm_v3)

5.0 5.0 5.0


### 题 4.4（余弦相似度）
计算向量 $\vec{a}, \vec{b}$ 的余弦相似度 $\cos\theta = \frac{\vec{a} \cdot \vec{b}}{\|\vec{a}\| \|\vec{b}\|}$

In [66]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
cos_sim = (a@b)/(np.sqrt(a@a)*np.sqrt(b@b))
print(cos_sim)  # 大约 0.9746

0.9746318461970762


### 题 4.5（转置与对称矩阵）
1. 给定矩阵 $A$，计算它的转置
2. 验证 $AA^T$ 是对称矩阵（即 $(AA^T)^T = AA^T$）

In [70]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

AT = A.T
print('A^T:')
print(AT)

S = A @ AT
print('A @ A^T:')
print(S)

# 验证 S 是否对称
is_symmetric = np.array_equal(S, S.T)
print('对称?', is_symmetric)  # True

A^T:
[[1 4]
 [2 5]
 [3 6]]
A @ A^T:
[[14 32]
 [32 77]]
对称? True


### 题 4.6（求逆和验证）
对一个 2×2 矩阵求逆，并验证 $A \cdot A^{-1} = I$

In [73]:
A = np.array([[4, 7],
              [2, 6]])

A_inv = np.linalginv.inv(A)
print('逆矩阵:')
print(A_inv)



AttributeError: module 'numpy' has no attribute 'linalginv'

### 题 4.7（求解线性方程组）
用矩阵求逆解线性方程组：
$$\begin{cases} 2x + 3y = 8 \\ x + 2y = 5 \end{cases}$$

提示：写成 $A\vec{x} = \vec{b}$ 形式，则 $\vec{x} = A^{-1}\vec{b}$

In [82]:
A = np.array([[2,3],
            [1,2]])
b = np.array([8,5])
x = np.linalg.inv(A)@b
print(x)  # 应该是 [1, 2]

[1. 2.]


### 题 4.8（特征值）
求矩阵 $A = \begin{bmatrix} 4 & 1 \\ 2 & 3 \end{bmatrix}$ 的特征值和特征向量

In [86]:
A = np.array([[4, 1],
              [2, 3]])

eigvals, eigvecs = np.linalg.eig(A)
print('特征值:', eigvals)
print('特征向量:')
print(eigvecs)

特征值: [5. 2.]
特征向量:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


---

## 模块 5：聚合函数与 axis（第 4 节，最容易踩坑）⭐⭐⭐

考点：sum、mean、std、max、argmax、axis 参数

### 题 5.1
对下面矩阵分别计算：全局总和、每列的和、每行的和

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print('全局总和:', ?)        # 45
print('每列的和:', ?)        # [12 15 18]
print('每行的和:', ?)        # [ 6 15 24]

### 题 5.2（axis 形状思考）
对一个 shape 为 `(4, 5)` 的矩阵，`A.sum(axis=0)` 和 `A.sum(axis=1)` 的形状分别是什么？

**先猜，再验证**

In [89]:
A = np.random.rand(4, 5)

# 你的猜测：
# A.sum(axis=0).shape = ?
# A.sum(axis=1).shape = ?

print(A.sum(axis=0).shape)
print(A.sum(axis=1).shape)

(5,)
(4,)


### 题 5.3（每行最大值）
找出矩阵 A 每一行的最大值

In [90]:
A = np.array([[3, 1, 4, 1, 5],
              [9, 2, 6, 5, 3],
              [5, 8, 9, 7, 9]])

row_max = np.max(A,axis=1)
print(row_max)  # [5 9 9]

[5 9 9]


### 题 5.4（每列均值与标准差）
计算下面数据矩阵中**每个特征（每列）**的均值和标准差

In [91]:
# 5 个样本，每个样本 3 个特征
X = np.array([[1.0, 200.0, 0.5],
              [2.0, 150.0, 0.7],
              [3.0, 180.0, 0.6],
              [4.0, 220.0, 0.8],
              [5.0, 170.0, 0.9]])

feature_mean = np.mean(X,axis=0)
feature_std = np.std(X,axis=0)
print('每列均值:', feature_mean)
print('每列标准差:', feature_std)

每列均值: [  3.  184.    0.7]
每列标准差: [ 1.41421356 24.16609195  0.14142136]


### 题 5.5（Z-score 标准化整列）
用题 5.4 的数据，把每一列做 Z-score 标准化（变成均值 0、标准差 1）。

**这一题考的是「广播」的萌芽**：把 shape (5,3) 的矩阵和 shape (3,) 的向量做运算

In [ ]:
X_std = 
print(X_std)
print('标准化后每列均值:', X_std.mean(axis=0))  # 应≈ [0 0 0]
print('标准化后每列标准差:', X_std.std(axis=0))  # 应≈ [1 1 1]

### 题 5.6（argmax）
找出矩阵每一行的最大值**所在的列索引**

In [ ]:
scores = np.array([[85, 92, 78],   # 第 1 个学生：语文85，数学92，英语78
                   [70, 88, 95],   # 第 2 个学生
                   [80, 75, 82]])  # 第 3 个学生

best_subject = ?
print(best_subject)  # [1 2 2]，分别表示数学、英语、英语

### 题 5.7（向量化思维：sigmoid）
实现 sigmoid 函数 $\sigma(x) = \frac{1}{1+e^{-x}}$，作用于一个数组的每个元素

**要求一行解决，不准用 for 循环**

In [ ]:
x = np.array([-3, -1, 0, 1, 3])

result = ?
print(result)
# 期望：[0.047 0.269 0.5 0.731 0.953]

### 题 5.8（向量化：softmax）
实现 softmax 函数 $\text{softmax}(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}}$（一维向量版本）

**性质**：输出每个分量在 (0,1)，且所有分量之和 = 1（可解释为概率分布）

In [ ]:
x = np.array([1.0, 2.0, 3.0, 4.0])

result = ?
print(result)
print('总和:', result.sum())  # 应该 = 1

### 题 5.9（向量化：MSE 损失函数）
实现均方误差（Mean Squared Error）：$\text{MSE} = \frac{1}{n}\sum_i (y_i - \hat{y}_i)^2$

In [ ]:
y_true = np.array([3.0, 5.0, 2.5, 7.0, 1.0])
y_pred = np.array([2.5, 5.0, 4.0, 8.0, 1.5])

mse = ?
print('MSE:', mse)  # 0.7

### 题 5.10（向量化：欧氏距离矩阵）⭐⭐⭐

给定一个数据集 $X$（n 个 d 维点），计算每两个点之间的欧氏距离 $d(x_i, x_j) = \|x_i - x_j\|_2$。

结果是一个 n×n 矩阵 $D$，$D_{ij}$ 是第 i 个点和第 j 个点的距离。

**先用 for 循环写一版，再思考能不能向量化**（向量化版本难度较高，做不出来不要紧，下一节广播会教）

In [ ]:
X = np.array([[0, 0],
              [3, 4],
              [1, 1],
              [5, 5]])
n = X.shape[0]

# 版本 1：双重循环
D = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        ?
print(D)

---

## 模块 6：索引与切片基础（第 5 节）⭐⭐

考点：单元素索引、切片、二维索引

### 题 6.1
对下面这个数组，分别取出：第 1 个元素、第 5 个元素、最后一个元素、倒数第 3 个元素

In [ ]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print('第 1 个:', ?)
print('第 5 个:', ?)
print('最后一个:', ?)
print('倒数第 3 个:', ?)

### 题 6.2（切片）
用切片完成：
1. 取前 3 个元素
2. 取最后 3 个元素
3. 取索引 2 到 7（不含 7）
4. 每隔一个元素取一个
5. 反转整个数组

In [ ]:
a = np.arange(10, 110, 10)  # [10 20 30 40 50 60 70 80 90 100]

print('前 3:', ?)
print('最后 3:', ?)
print('索引 2-6:', ?)
print('每隔一个:', ?)
print('反转:', ?)

### 题 6.3（视图陷阱 ⚠️）

运行下面代码，**先猜输出是什么**，再验证。然后修改代码，让 a 不被改变。

In [ ]:
# 你的猜测：a 会变成什么？
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 999
print('a =', a)
print('b =', b)

# 修改下面代码，让 a 不受影响
a = np.array([1, 2, 3, 4, 5])
b = ?
b[0] = 999
print('a =', a)  # 应该是 [1 2 3 4 5]
print('b =', b)  # 应该是 [999 3 4]

### 题 6.4（二维索引）

对下面 5×5 矩阵，分别取出：
1. 第 2 行第 3 列那个元素
2. 整个第 1 行
3. 整个第 4 列
4. 左上角 3×3 子矩阵
5. 右下角 2×2 子矩阵
6. 最后一行最后一个元素

In [ ]:
M = np.arange(1, 26).reshape(5, 5)
print(M)
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]
#  [16 17 18 19 20]
#  [21 22 23 24 25]]

print('第 2 行第 3 列:', ?)
print('第 1 行:', ?)
print('第 4 列:', ?)
print('左上 3x3:')
print(?)
print('右下 2x2:')
print(?)
print('最后一个元素:', ?)

### 题 6.5（形状对比）
下面四种取列的写法，得到的结果 shape 分别是什么？

In [ ]:
M = np.arange(1, 13).reshape(3, 4)

v1 = M[:, 0]      # 一维切片
v2 = M[:, 0:1]    # 二维切片
v3 = M[0, :]
v4 = M[0:1, :]

print(v1.shape, v2.shape, v3.shape, v4.shape)
# 思考：什么时候用降维（一维），什么时候保持二维？

### 题 6.6（reshape 改变形状）

1. 把一个长度 12 的一维数组变成 3×4 矩阵
2. 再变成 4×3 矩阵
3. 再变成 2×2×3 三维张量
4. 用 -1 让 NumPy 自动推断维度（变成 6 行）

In [ ]:
a = np.arange(12)

print('3x4:')
print(?)

print('4x3:')
print(?)

print('2x2x3:')
print(?)

print('6 行（用 -1 自动推断列）:')
print(?)

---

## 模块 7：布尔索引与花式索引（第 5 节核心）⭐⭐⭐

考点：条件筛选、`& | ~`、条件赋值、花式索引

### 题 7.1
从下面数组中筛选出所有偶数

In [111]:
a = np.array([12, 7, 5, 22, 33, 18, 9, 50, 4, 17])
evens = a % 2 == 0
print(a[evens])  # [12 22 18 50  4]

[12 22 18 50  4]


### 题 7.2
从一个一维数组中找出所有 30 到 70 之间的值（含端点）

**注意**：使用 `&` 而非 `and`，每个条件加括号

In [ ]:
data = np.array([15, 42, 88, 23, 55, 67, 91, 30, 70, 5])
result = ?
print(result)  # [42 55 67 30 70]

### 题 7.3（条件赋值）
把数组中所有奇数替换为 -1

In [ ]:
arr = np.arange(1, 11)
?
print(arr)  # [-1  2 -1  4 -1  6 -1  8 -1 10]

### 题 7.4（异常值截断 / Winsorize）

应统人最熟的操作：把数据中超过 3σ 的值截断为 mean ± 3σ

In [ ]:
np.random.seed(0)
data = np.random.randn(1000) * 5 + 50
# 加几个极端异常值
data[10] = 200
data[20] = -100

mean = data.mean()
std = data.std()

# 把大于 mean+3σ 的截断为 mean+3σ
?
# 把小于 mean-3σ 的截断为 mean-3σ
?

print('截断后最大值:', data.max())
print('截断后最小值:', data.min())

### 题 7.5（缺失值处理）

把数组中的 NaN 替换为该数组的均值（NaN 之外的均值）

提示：用 `np.isnan` 判断哪些是 NaN，用 `np.nanmean` 计算忽略 NaN 的均值

In [ ]:
data = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan, 7.0])

valid_mean = ?
data[?] = valid_mean
print(data)

### 题 7.6（多条件 SQL 风格筛选）

给定身高和性别数据，筛选出**男性中身高 > 175** 的人数

In [ ]:
heights = np.array([165, 178, 182, 158, 173, 165, 190, 168, 177, 162])
genders = np.array([0,   1,   1,   0,   1,   0,   1,   0,   1,   0])  # 0=女 1=男

tall_males = ?
print('身高>175 的男性:', tall_males)
print('人数:', len(tall_males))

### 题 7.7（分组统计）
用题 7.6 的数据：
1. 计算男性平均身高
2. 计算女性平均身高

In [ ]:
male_avg = ?
female_avg = ?
print(f'男性平均身高: {male_avg}')
print(f'女性平均身高: {female_avg}')

### 题 7.8（花式索引）
从下面数组中**按指定顺序**取出第 0、第 5、第 2、第 8 个元素

In [ ]:
a = np.arange(10, 100, 10)  # [10 20 30 40 50 60 70 80 90]
result = ?
print(result)  # [10 60 30 90]

### 题 7.9（花式索引取行）
从矩阵中按顺序取第 0、第 2、第 4 行

In [ ]:
M = np.arange(1, 26).reshape(5, 5)
rows = ?
print(rows)

### 题 7.10（np.where 三元运算）

`np.where(condition, x, y)` 类似三元运算符：满足 condition 取 x，否则取 y

用 np.where 实现：把数组中的负数变成 0，正数保持不变（ReLU 激活函数）

In [ ]:
x = np.array([-3, -1, 0, 2, 5, -7, 4])
relu = ?
print(relu)  # [0 0 0 2 5 0 4]

### 题 7.11（综合：成绩分级）

用 `np.where` 把成绩分为：
- ≥90: 'A'
- 80-89: 'B'  
- 70-79: 'C'
- <70: 'D'

提示：嵌套 np.where

In [ ]:
scores = np.array([95, 72, 88, 60, 91, 78, 85])
grades = ?
print(grades)  # ['A' 'C' 'B' 'D' 'A' 'C' 'B']

---

## 模块 8：综合应用题（应统场景）⭐⭐⭐⭐

把前面所有知识点串起来用

### 题 8.1（应用：手写实现样本协方差矩阵）

给定数据矩阵 $X$（n 行 = 样本，p 列 = 特征），手动计算样本协方差矩阵 $S$，公式：

$$S = \frac{1}{n-1} (X - \bar{X})^T (X - \bar{X})$$

其中 $\bar{X}$ 是每列的均值（重复 n 次构成的矩阵）。

最后用 `np.cov(X, rowvar=False)` 验证你的结果。

In [105]:
np.random.seed(42)
X = np.random.randn(100, 3)  # 100 个样本，3 个特征

# 你的实现
n = X.shape[0]
X_bar = np.sum(X,axis = 0)/n
S = ((X - X_bar).T@(X - X_bar))/(n-1)
print(S)
# 用 np.cov 验证
S_np = np.cov(X, rowvar=False)
print('numpy 协方差矩阵:')
print(S_np)

# 验证两者非常接近
print('差异:', np.abs(S - S_np).max())

[[ 0.68029352 -0.03927641 -0.1108006 ]
 [-0.03927641  0.9586369  -0.1348594 ]
 [-0.1108006  -0.1348594   1.23856849]]
numpy 协方差矩阵:
[[ 0.68029352 -0.03927641 -0.1108006 ]
 [-0.03927641  0.9586369  -0.1348594 ]
 [-0.1108006  -0.1348594   1.23856849]]
差异: 2.220446049250313e-16


### 题 8.2（应用：手写实现线性回归）

用 NumPy 实现最小二乘线性回归。

公式：$\hat{\beta} = (X^T X)^{-1} X^T y$

（应统人对这个公式应该非常熟）

In [107]:
np.random.seed(0)
n = 100
X = np.random.randn(n, 3)
true_beta = np.array([1.5, -2.0, 0.8])
y = X @ true_beta + np.random.randn(n) * 0.1  # 加点噪声

# 用最小二乘法估计 beta
beta_hat = np.linalg.inv(X.T@X)@X.T@y
print('真实 β:', true_beta)
print('估计 β:', beta_hat)
# 应该非常接近

真实 β: [ 1.5 -2.   0.8]
估计 β: [ 1.49371939 -2.00708947  0.80661857]


### 题 8.3（应用：抛硬币模拟大数定律）

模拟抛 10000 次公平硬币（正面=1，反面=0），
1. 计算每抛 n 次（n=1, 2, ..., 10000）的累计正面比例
2. 验证：随着 n 增大，比例趋近 0.5

提示：用 `np.cumsum` 计算累计求和，再除以 `np.arange(1, n+1)`

In [112]:
np.random.seed(42)
flips = np.random.randint(0, 2, size=10000)  # 0 或 1

cumulative_ratio = np.cumsum(flips) / np.arange(1, len(flips) + 1)

# 输出前 10 次和最后 5 次的累计比例
print('前 10 次:', cumulative_ratio[:10])
print('最后 5 次:', cumulative_ratio[-5:])  # 应该非常接近 0.5

前 10 次: [0.         0.5        0.33333333 0.25       0.2        0.33333333
 0.28571429 0.25       0.22222222 0.3       ]
最后 5 次: [0.49869948 0.49864959 0.49869974 0.49874987 0.4987    ]


### 题 8.4（应用：分类准确率）

给定真实标签和模型预测，计算分类准确率

In [113]:
y_true = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0])
y_pred = np.array([0, 1, 0, 0, 1, 1, 0, 1, 1, 0])

accuracy = (y_true == y_pred).sum()/len(y_pred)
print(f'准确率: {accuracy:.2%}')  # 80%

准确率: 80.00%


### 题 8.5（应用：混淆矩阵）⭐⭐⭐⭐

对二分类任务，构建 2×2 混淆矩阵：

$$\begin{bmatrix} \text{TN} & \text{FP} \\ \text{FN} & \text{TP} \end{bmatrix}$$

- TN: 真实 0，预测 0
- FP: 真实 0，预测 1
- FN: 真实 1，预测 0
- TP: 真实 1，预测 1

In [119]:
y_true = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])
y_pred = np.array([0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0])

TN = ((y_true == 0) & (y_pred == 0)).sum()
FP = ((y_true == 0) & (y_pred == 1)).sum()
FN = ((y_true == 1) & (y_pred == 0)).sum()
TP = ((y_true == 1) & (y_pred == 1)).sum()

confusion_matrix = np.array([[TN, FP], [FN, TP]])
print('混淆矩阵:')
print(confusion_matrix)

# 计算精确率 Precision = TP/(TP+FP) 和召回率 Recall = TP/(TP+FN)
precision = TP/(TP+FP)
recall = TP/(TP+FN)
print(f'精确率: {precision:.3f}')
print(f'召回率: {recall:.3f}')

混淆矩阵:
[[5 1]
 [2 4]]
精确率: 0.800
召回率: 0.667


### 题 8.6（应用：top-k 推荐）

给定每个用户对所有商品的预测评分，找出每个用户**评分最高的前 3 个商品索引**。

提示：用 `np.argsort` 排序后取最后 3 个，或用 `np.argpartition`

In [130]:
np.random.seed(0)
# 5 个用户对 10 个商品的预测评分
scores = np.random.rand(5, 10)
print('评分矩阵:')
print(scores.round(2))

# 每个用户的 top-3 商品
top3_per_user = np.argsort(-scores, axis=1)[:, :3]
print('每个用户的 top-3 商品索引:')
print(top3_per_user)

评分矩阵:
[[0.55 0.72 0.6  0.54 0.42 0.65 0.44 0.89 0.96 0.38]
 [0.79 0.53 0.57 0.93 0.07 0.09 0.02 0.83 0.78 0.87]
 [0.98 0.8  0.46 0.78 0.12 0.64 0.14 0.94 0.52 0.41]
 [0.26 0.77 0.46 0.57 0.02 0.62 0.61 0.62 0.94 0.68]
 [0.36 0.44 0.7  0.06 0.67 0.67 0.21 0.13 0.32 0.36]]
每个用户的 top-3 商品索引:
[[8 7 1]
 [3 9 7]
 [0 7 1]
 [8 1 9]
 [2 5 4]]


### 题 8.7（终极挑战：手写 K-Means 一步迭代）⭐⭐⭐⭐

K-Means 算法的一步迭代：
1. 给定数据点 X 和 k 个聚类中心 centers
2. 把每个数据点分配到最近的中心（每个点的标签）
3. 用每个簇的均值作为新中心

**这一题综合了：距离计算、argmin、布尔索引、按 axis 求均值**

In [ ]:
np.random.seed(42)
# 30 个二维点
X = np.random.randn(30, 2)
# 3 个初始中心
centers = np.array([[0., 0.], [2., 2.], [-2., -2.]])
k = 3

# 第 1 步：计算每个点到每个中心的距离（用循环也可以）
distances = np.zeros((30, k))
for j in range(k):
    distances[:, j] = ?  # 第 j 列：所有点到中心 j 的距离

# 第 2 步：每个点分配到最近的中心
labels = ?
print('前 10 个点的标签:', labels[:10])

# 第 3 步：更新中心（每个簇的均值）
new_centers = np.zeros_like(centers)
for j in range(k):
    new_centers[j] = ?  # 第 j 个簇的均值

print('新中心:')
print(new_centers)

---

## 🎉 完成检查清单

做完所有题目后，对照下面这份清单自我检查：

### 概念理解
- [ ] 能说出 NumPy 数组与 Python list 的 3 个区别
- [ ] 能解释 `*` 和 `@` 的不同含义
- [ ] 能解释 `(3,)`、`(1,3)`、`(3,1)` 的区别
- [ ] 能说出 `axis=0` 是「消掉哪个维度」
- [ ] 能说出切片返回的是视图还是副本，以及为什么

### 操作熟练
- [ ] 不查文档能创建各种数组（zeros/ones/eye/arange/linspace/random）
- [ ] 能熟练写出二维矩阵的子矩阵提取
- [ ] 能熟练写多条件布尔筛选（注意 `&` `|` `~` 和括号）
- [ ] 能用一行代码实现 sigmoid、softmax、ReLU、MSE
- [ ] 能用矩阵公式实现线性回归

### 应统场景熟练
- [ ] 能用 NumPy 做标准化、异常值截断、缺失值填补
- [ ] 能用 NumPy 计算样本协方差矩阵
- [ ] 能用 NumPy 做蒙特卡洛模拟

---

## 📚 答案与提示

**做完后**告诉 Claude「我做完了」，他会给你逐题答案 + 讲解你卡住的地方。

**强烈建议**：先全部做完再看答案。卡住的地方记下来，专门讨论，效果最好。