# NumPy 综合练习题（第 1-5 节）

**说明**：
- 本练习覆盖第 1-5 节**所有知识点**，按章节顺序排列
- 共 **8 大模块，60+ 题**，难度从 ⭐ 到 ⭐⭐⭐⭐
- 每题先想清楚**数学含义**，再写代码
- 卡住超过 5 分钟可以问 Claude，但**先自己尝试**
- 完成后对照答案（最后会给）

**预计完成时间**：4-6 小时（建议分两天做）

---

## 模块 0：环境准备

运行下面这个 cell 导入 NumPy。

In [ ]:
import numpy as np
print(np.__version__)  # 看看你的 NumPy 版本

---

## 模块 1：理解 NumPy 与 List 的区别（第 1 节）⭐

考点：NumPy 重新定义了运算符的含义

### 题 1.1

已有两个 Python list：`a = [1, 2, 3]`，`b = [4, 5, 6]`。  
请分别用 **list** 和 **NumPy 数组** 计算它们的「逐元素相加」，对比输出。

In [ ]:
# Python list 的加法（不是逐元素加）
a = [1, 2, 3]
b = [4, 5, 6]
print('list 加法:', ?)

# NumPy 数组的加法（逐元素）
a_np = ?
b_np = ?
print('numpy 加法:', ?)

### 题 1.2

用**纯 Python 循环**实现两个 list 的逐元素相乘，再用 NumPy 一行实现，对比代码长度。

In [ ]:
# 纯 Python 写法
a = [1, 2, 3, 4]
b = [10, 20, 30, 40]
result_py = ?
print(result_py)

# NumPy 写法
result_np = ?
print(result_np)

---

## 模块 2：创建数组（第 2 节）⭐

考点：array、zeros、ones、eye、arange、linspace、随机数

### 题 2.1
创建一个一维 NumPy 数组：`[10, 20, 30, 40, 50]`

In [ ]:
a = ?
print(a)

### 题 2.2
创建一个 3 行 4 列的矩阵，第一行 [1,2,3,4]，第二行 [5,6,7,8]，第三行 [9,10,11,12]

In [ ]:
M = ?
print(M)

### 题 2.3
创建一个 5×5 的零矩阵

In [ ]:
Z = ?
print(Z)

### 题 2.4
创建一个 4×4 的全 1 矩阵，且**数据类型为整数**（不要小数点）

In [ ]:
O = ?
print(O)
print(O.dtype)  # 应该是 int

### 题 2.5
创建一个 6×6 的单位矩阵 $I_6$

In [ ]:
I = ?
print(I)

### 题 2.6
用 `np.arange` 生成 `[2, 5, 8, 11, 14, 17, 20]`（提示：起点 2，步长 3）

In [ ]:
x = ?
print(x)

### 题 2.7
用 `np.linspace` 在 $[0, \pi]$ 上均匀取 11 个点

In [ ]:
x = ?
print(x)

### 题 2.8
（统计模拟）用 `np.random.seed(42)` 设种子，然后从 $N(0, 1)$ 抽 10000 个样本，验证均值 $\approx 0$，方差 $\approx 1$

In [ ]:
np.random.seed(42)
samples = ?
print('均值:', ?)
print('方差:', ?)

### 题 2.9
从 $N(\mu=100, \sigma=15)$ 抽 1000 个样本（提示：用 `np.random.normal`，注意参数名 `loc` 和 `scale`）

In [ ]:
samples = ?
print('均值:', samples.mean())  # 应该 ≈ 100
print('标准差:', samples.std())  # 应该 ≈ 15

### 题 2.10（蒙特卡洛模拟）
用 100 万个随机点估计 $\pi$。

**思路**：在 $[-1, 1] \times [-1, 1]$ 正方形内随机撒点，落在单位圆内的比例 $\approx \pi/4$

In [ ]:
np.random.seed(0)
n = 1000000
x = ?  # U(-1, 1) 抽 n 个
y = ?  # 同上
inside = ?  # 落在 x²+y²<1 内的点数
pi_estimate = ?
print(f'π 估计值: {pi_estimate}')

---

## 模块 3：数组的核心属性（第 3 节）⭐

考点：shape、ndim、dtype、size、形状的陷阱

### 题 3.1
对下面这个数组，输出它的 shape、ndim、dtype、size

In [ ]:
A = np.array([[1.5, 2.5, 3.5],
              [4.5, 5.5, 6.5]])
print('shape:', ?)
print('ndim:', ?)
print('dtype:', ?)
print('size:', ?)

### 题 3.2（形状陷阱）
下面三个数组的 shape 分别是什么？**先猜，再验证**

In [ ]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([[1, 2, 3, 4]])
v3 = np.array([[1], [2], [3], [4]])

# 你的猜测：
# v1.shape = ?
# v2.shape = ?
# v3.shape = ?

# 验证：
print(v1.shape, v2.shape, v3.shape)

### 题 3.3
创建一个数组 `[1, 2, 3]`，dtype 为 `float32`（深度学习常用）

In [ ]:
a = ?
print(a)
print(a.dtype)  # 应该是 float32

### 题 3.4
把一个 float 数组转换为 int 数组（用 `.astype`）

In [ ]:
a = np.array([1.7, 2.3, 3.9, 4.1])
b = ?
print(b)        # 注意：转 int 是直接截断小数部分（向 0 截断）
print(b.dtype)  # int

### 题 3.5（思考题，无需写代码）

下面这个数组的 shape 是什么？**先想，再验证**

```python
X = np.zeros((2, 3, 4))
```

提示：这是 3 维数组（张量），可以理解为 "2 个 3×4 的矩阵叠在一起"

In [ ]:
X = np.zeros((2, 3, 4))
print(X.shape)
print(X.ndim)
print(X.size)  # 应该是 2×3×4 = 24

---

## 模块 4：基础运算（第 4 节，逐元素 vs 矩阵乘法）⭐⭐

考点：`+ - * /` 的逐元素含义、`@` 矩阵乘法、转置、求逆

### 题 4.1
给定 $\vec{a} = [1, 2, 3, 4]$，$\vec{b} = [5, 6, 7, 8]$，计算：
1. 逐元素加 $\vec{a} + \vec{b}$
2. 逐元素乘（Hadamard 积）$\vec{a} \odot \vec{b}$
3. 内积 $\vec{a} \cdot \vec{b}$

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print('逐元素加:', ?)
print('Hadamard 积:', ?)
print('内积:', ?)  # 应该是 1*5+2*6+3*7+4*8 = 70

### 题 4.2（关键：`*` vs `@`）
对下面两个矩阵分别计算 `A * B` 和 `A @ B`，**说出它们的区别**

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print('A * B (Hadamard 积):')
print(?)

print('A @ B (矩阵乘法):')
print(?)

# 验证矩阵乘法：手算 (A@B)[0][0] 应该等于 1*5 + 2*7 = ?

### 题 4.3（L2 范数）
计算向量 $\vec{x} = [3, 4]$ 的 L2 范数 $\|\vec{x}\|_2 = \sqrt{x_1^2 + x_2^2}$

**用 3 种方法**：
1. 用 `np.sqrt` 和 `np.sum`
2. 用 `np.sqrt` 和内积 `@`
3. 用 `np.linalg.norm`

In [ ]:
x = np.array([3, 4])

norm_v1 = ?
norm_v2 = ?
norm_v3 = ?

print(norm_v1, norm_v2, norm_v3)  # 都应该是 5.0

### 题 4.4（余弦相似度）
计算向量 $\vec{a}, \vec{b}$ 的余弦相似度 $\cos\theta = \frac{\vec{a} \cdot \vec{b}}{\|\vec{a}\| \|\vec{b}\|}$

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
cos_sim = ?
print(cos_sim)  # 大约 0.9746

### 题 4.5（转置与对称矩阵）
1. 给定矩阵 $A$，计算它的转置
2. 验证 $AA^T$ 是对称矩阵（即 $(AA^T)^T = AA^T$）

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

AT = ?
print('A^T:')
print(AT)

S = A @ AT
print('A @ A^T:')
print(S)

# 验证 S 是否对称
is_symmetric = ?
print('对称?', is_symmetric)  # True

### 题 4.6（求逆和验证）
对一个 2×2 矩阵求逆，并验证 $A \cdot A^{-1} = I$

In [ ]:
A = np.array([[4, 7],
              [2, 6]])

A_inv = ?
print('逆矩阵:')
print(A_inv)

# 验证：A @ A_inv 应该 ≈ 单位矩阵
print('验证:')
print(?)

### 题 4.7（求解线性方程组）
用矩阵求逆解线性方程组：
$$\begin{cases} 2x + 3y = 8 \\ x + 2y = 5 \end{cases}$$

提示：写成 $A\vec{x} = \vec{b}$ 形式，则 $\vec{x} = A^{-1}\vec{b}$

In [ ]:
A = ?
b = ?
x = ?
print(x)  # 应该是 [1, 2]

### 题 4.8（特征值）
求矩阵 $A = \begin{bmatrix} 4 & 1 \\ 2 & 3 \end{bmatrix}$ 的特征值和特征向量

In [ ]:
A = np.array([[4, 1],
              [2, 3]])

eigvals, eigvecs = ?
print('特征值:', eigvals)
print('特征向量:')
print(eigvecs)

---

## 模块 5：聚合函数与 axis（第 4 节，最容易踩坑）⭐⭐⭐

考点：sum、mean、std、max、argmax、axis 参数

### 题 5.1
对下面矩阵分别计算：全局总和、每列的和、每行的和

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print('全局总和:', ?)        # 45
print('每列的和:', ?)        # [12 15 18]
print('每行的和:', ?)        # [ 6 15 24]

### 题 5.2（axis 形状思考）
对一个 shape 为 `(4, 5)` 的矩阵，`A.sum(axis=0)` 和 `A.sum(axis=1)` 的形状分别是什么？

**先猜，再验证**

In [ ]:
A = np.random.rand(4, 5)

# 你的猜测：
# A.sum(axis=0).shape = ?
# A.sum(axis=1).shape = ?

print(A.sum(axis=0).shape)
print(A.sum(axis=1).shape)

### 题 5.3（每行最大值）
找出矩阵 A 每一行的最大值

In [ ]:
A = np.array([[3, 1, 4, 1, 5],
              [9, 2, 6, 5, 3],
              [5, 8, 9, 7, 9]])

row_max = ?
print(row_max)  # [5 9 9]

### 题 5.4（每列均值与标准差）
计算下面数据矩阵中**每个特征（每列）**的均值和标准差

In [ ]:
# 5 个样本，每个样本 3 个特征
X = np.array([[1.0, 200.0, 0.5],
              [2.0, 150.0, 0.7],
              [3.0, 180.0, 0.6],
              [4.0, 220.0, 0.8],
              [5.0, 170.0, 0.9]])

feature_mean = ?
feature_std = ?
print('每列均值:', feature_mean)
print('每列标准差:', feature_std)

### 题 5.5（Z-score 标准化整列）
用题 5.4 的数据，把每一列做 Z-score 标准化（变成均值 0、标准差 1）。

**这一题考的是「广播」的萌芽**：把 shape (5,3) 的矩阵和 shape (3,) 的向量做运算

In [ ]:
X_std = ?
print(X_std)
print('标准化后每列均值:', X_std.mean(axis=0))  # 应≈ [0 0 0]
print('标准化后每列标准差:', X_std.std(axis=0))  # 应≈ [1 1 1]

### 题 5.6（argmax）
找出矩阵每一行的最大值**所在的列索引**

In [ ]:
scores = np.array([[85, 92, 78],   # 第 1 个学生：语文85，数学92，英语78
                   [70, 88, 95],   # 第 2 个学生
                   [80, 75, 82]])  # 第 3 个学生

best_subject = ?
print(best_subject)  # [1 2 2]，分别表示数学、英语、英语

### 题 5.7（向量化思维：sigmoid）
实现 sigmoid 函数 $\sigma(x) = \frac{1}{1+e^{-x}}$，作用于一个数组的每个元素

**要求一行解决，不准用 for 循环**

In [ ]:
x = np.array([-3, -1, 0, 1, 3])

result = ?
print(result)
# 期望：[0.047 0.269 0.5 0.731 0.953]

### 题 5.8（向量化：softmax）
实现 softmax 函数 $\text{softmax}(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}}$（一维向量版本）

**性质**：输出每个分量在 (0,1)，且所有分量之和 = 1（可解释为概率分布）

In [ ]:
x = np.array([1.0, 2.0, 3.0, 4.0])

result = ?
print(result)
print('总和:', result.sum())  # 应该 = 1

### 题 5.9（向量化：MSE 损失函数）
实现均方误差（Mean Squared Error）：$\text{MSE} = \frac{1}{n}\sum_i (y_i - \hat{y}_i)^2$

In [ ]:
y_true = np.array([3.0, 5.0, 2.5, 7.0, 1.0])
y_pred = np.array([2.5, 5.0, 4.0, 8.0, 1.5])

mse = ?
print('MSE:', mse)  # 0.7

### 题 5.10（向量化：欧氏距离矩阵）⭐⭐⭐

给定一个数据集 $X$（n 个 d 维点），计算每两个点之间的欧氏距离 $d(x_i, x_j) = \|x_i - x_j\|_2$。

结果是一个 n×n 矩阵 $D$，$D_{ij}$ 是第 i 个点和第 j 个点的距离。

**先用 for 循环写一版，再思考能不能向量化**（向量化版本难度较高，做不出来不要紧，下一节广播会教）

In [ ]:
X = np.array([[0, 0],
              [3, 4],
              [1, 1],
              [5, 5]])
n = X.shape[0]

# 版本 1：双重循环
D = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        ?
print(D)

---

## 模块 6：索引与切片基础（第 5 节）⭐⭐

考点：单元素索引、切片、二维索引

### 题 6.1
对下面这个数组，分别取出：第 1 个元素、第 5 个元素、最后一个元素、倒数第 3 个元素

In [ ]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print('第 1 个:', ?)
print('第 5 个:', ?)
print('最后一个:', ?)
print('倒数第 3 个:', ?)

### 题 6.2（切片）
用切片完成：
1. 取前 3 个元素
2. 取最后 3 个元素
3. 取索引 2 到 7（不含 7）
4. 每隔一个元素取一个
5. 反转整个数组

In [ ]:
a = np.arange(10, 110, 10)  # [10 20 30 40 50 60 70 80 90 100]

print('前 3:', ?)
print('最后 3:', ?)
print('索引 2-6:', ?)
print('每隔一个:', ?)
print('反转:', ?)

### 题 6.3（视图陷阱 ⚠️）

运行下面代码，**先猜输出是什么**，再验证。然后修改代码，让 a 不被改变。

In [ ]:
# 你的猜测：a 会变成什么？
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 999
print('a =', a)
print('b =', b)

# 修改下面代码，让 a 不受影响
a = np.array([1, 2, 3, 4, 5])
b = ?
b[0] = 999
print('a =', a)  # 应该是 [1 2 3 4 5]
print('b =', b)  # 应该是 [999 3 4]

### 题 6.4（二维索引）

对下面 5×5 矩阵，分别取出：
1. 第 2 行第 3 列那个元素
2. 整个第 1 行
3. 整个第 4 列
4. 左上角 3×3 子矩阵
5. 右下角 2×2 子矩阵
6. 最后一行最后一个元素

In [ ]:
M = np.arange(1, 26).reshape(5, 5)
print(M)
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]
#  [16 17 18 19 20]
#  [21 22 23 24 25]]

print('第 2 行第 3 列:', ?)
print('第 1 行:', ?)
print('第 4 列:', ?)
print('左上 3x3:')
print(?)
print('右下 2x2:')
print(?)
print('最后一个元素:', ?)

### 题 6.5（形状对比）
下面四种取列的写法，得到的结果 shape 分别是什么？

In [ ]:
M = np.arange(1, 13).reshape(3, 4)

v1 = M[:, 0]      # 一维切片
v2 = M[:, 0:1]    # 二维切片
v3 = M[0, :]
v4 = M[0:1, :]

print(v1.shape, v2.shape, v3.shape, v4.shape)
# 思考：什么时候用降维（一维），什么时候保持二维？

### 题 6.6（reshape 改变形状）

1. 把一个长度 12 的一维数组变成 3×4 矩阵
2. 再变成 4×3 矩阵
3. 再变成 2×2×3 三维张量
4. 用 -1 让 NumPy 自动推断维度（变成 6 行）

In [ ]:
a = np.arange(12)

print('3x4:')
print(?)

print('4x3:')
print(?)

print('2x2x3:')
print(?)

print('6 行（用 -1 自动推断列）:')
print(?)

---

## 模块 7：布尔索引与花式索引（第 5 节核心）⭐⭐⭐

考点：条件筛选、`& | ~`、条件赋值、花式索引

### 题 7.1
从下面数组中筛选出所有偶数

In [ ]:
a = np.array([12, 7, 5, 22, 33, 18, 9, 50, 4, 17])
evens = ?
print(evens)  # [12 22 18 50  4]

### 题 7.2
从一个一维数组中找出所有 30 到 70 之间的值（含端点）

**注意**：使用 `&` 而非 `and`，每个条件加括号

In [ ]:
data = np.array([15, 42, 88, 23, 55, 67, 91, 30, 70, 5])
result = ?
print(result)  # [42 55 67 30 70]

### 题 7.3（条件赋值）
把数组中所有奇数替换为 -1

In [ ]:
arr = np.arange(1, 11)
?
print(arr)  # [-1  2 -1  4 -1  6 -1  8 -1 10]

### 题 7.4（异常值截断 / Winsorize）

应统人最熟的操作：把数据中超过 3σ 的值截断为 mean ± 3σ

In [ ]:
np.random.seed(0)
data = np.random.randn(1000) * 5 + 50
# 加几个极端异常值
data[10] = 200
data[20] = -100

mean = data.mean()
std = data.std()

# 把大于 mean+3σ 的截断为 mean+3σ
?
# 把小于 mean-3σ 的截断为 mean-3σ
?

print('截断后最大值:', data.max())
print('截断后最小值:', data.min())

### 题 7.5（缺失值处理）

把数组中的 NaN 替换为该数组的均值（NaN 之外的均值）

提示：用 `np.isnan` 判断哪些是 NaN，用 `np.nanmean` 计算忽略 NaN 的均值

In [ ]:
data = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan, 7.0])

valid_mean = ?
data[?] = valid_mean
print(data)

### 题 7.6（多条件 SQL 风格筛选）

给定身高和性别数据，筛选出**男性中身高 > 175** 的人数

In [ ]:
heights = np.array([165, 178, 182, 158, 173, 165, 190, 168, 177, 162])
genders = np.array([0,   1,   1,   0,   1,   0,   1,   0,   1,   0])  # 0=女 1=男

tall_males = ?
print('身高>175 的男性:', tall_males)
print('人数:', len(tall_males))

### 题 7.7（分组统计）
用题 7.6 的数据：
1. 计算男性平均身高
2. 计算女性平均身高

In [ ]:
male_avg = ?
female_avg = ?
print(f'男性平均身高: {male_avg}')
print(f'女性平均身高: {female_avg}')

### 题 7.8（花式索引）
从下面数组中**按指定顺序**取出第 0、第 5、第 2、第 8 个元素

In [ ]:
a = np.arange(10, 100, 10)  # [10 20 30 40 50 60 70 80 90]
result = ?
print(result)  # [10 60 30 90]

### 题 7.9（花式索引取行）
从矩阵中按顺序取第 0、第 2、第 4 行

In [ ]:
M = np.arange(1, 26).reshape(5, 5)
rows = ?
print(rows)

### 题 7.10（np.where 三元运算）

`np.where(condition, x, y)` 类似三元运算符：满足 condition 取 x，否则取 y

用 np.where 实现：把数组中的负数变成 0，正数保持不变（ReLU 激活函数）

In [ ]:
x = np.array([-3, -1, 0, 2, 5, -7, 4])
relu = ?
print(relu)  # [0 0 0 2 5 0 4]

### 题 7.11（综合：成绩分级）

用 `np.where` 把成绩分为：
- ≥90: 'A'
- 80-89: 'B'  
- 70-79: 'C'
- <70: 'D'

提示：嵌套 np.where

In [ ]:
scores = np.array([95, 72, 88, 60, 91, 78, 85])
grades = ?
print(grades)  # ['A' 'C' 'B' 'D' 'A' 'C' 'B']

---

## 模块 8：综合应用题（应统场景）⭐⭐⭐⭐

把前面所有知识点串起来用

### 题 8.1（应用：手写实现样本协方差矩阵）

给定数据矩阵 $X$（n 行 = 样本，p 列 = 特征），手动计算样本协方差矩阵 $S$，公式：

$$S = \frac{1}{n-1} (X - \bar{X})^T (X - \bar{X})$$

其中 $\bar{X}$ 是每列的均值（重复 n 次构成的矩阵）。

最后用 `np.cov(X, rowvar=False)` 验证你的结果。

In [ ]:
np.random.seed(42)
X = np.random.randn(100, 3)  # 100 个样本，3 个特征

# 你的实现
n = X.shape[0]
X_centered = ?
S_my = ?
print('我的协方差矩阵:')
print(S_my)

# 用 np.cov 验证
S_np = np.cov(X, rowvar=False)
print('numpy 协方差矩阵:')
print(S_np)

# 验证两者非常接近
print('差异:', np.abs(S_my - S_np).max())

### 题 8.2（应用：手写实现线性回归）

用 NumPy 实现最小二乘线性回归。

公式：$\hat{\beta} = (X^T X)^{-1} X^T y$

（应统人对这个公式应该非常熟）

In [ ]:
np.random.seed(0)
n = 100
X = np.random.randn(n, 3)
true_beta = np.array([1.5, -2.0, 0.8])
y = X @ true_beta + np.random.randn(n) * 0.1  # 加点噪声

# 用最小二乘法估计 beta
beta_hat = ?
print('真实 β:', true_beta)
print('估计 β:', beta_hat)
# 应该非常接近

### 题 8.3（应用：抛硬币模拟大数定律）

模拟抛 10000 次公平硬币（正面=1，反面=0），
1. 计算每抛 n 次（n=1, 2, ..., 10000）的累计正面比例
2. 验证：随着 n 增大，比例趋近 0.5

提示：用 `np.cumsum` 计算累计求和，再除以 `np.arange(1, n+1)`

In [ ]:
np.random.seed(42)
flips = np.random.randint(0, 2, size=10000)  # 0 或 1

cumulative_ratio = ?

# 输出前 10 次和最后 5 次的累计比例
print('前 10 次:', cumulative_ratio[:10])
print('最后 5 次:', cumulative_ratio[-5:])  # 应该非常接近 0.5

### 题 8.4（应用：分类准确率）

给定真实标签和模型预测，计算分类准确率

In [ ]:
y_true = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0])
y_pred = np.array([0, 1, 0, 0, 1, 1, 0, 1, 1, 0])

accuracy = ?
print(f'准确率: {accuracy:.2%}')  # 80%

### 题 8.5（应用：混淆矩阵）⭐⭐⭐⭐

对二分类任务，构建 2×2 混淆矩阵：

$$\begin{bmatrix} \text{TN} & \text{FP} \\ \text{FN} & \text{TP} \end{bmatrix}$$

- TN: 真实 0，预测 0
- FP: 真实 0，预测 1
- FN: 真实 1，预测 0
- TP: 真实 1，预测 1

In [ ]:
y_true = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])
y_pred = np.array([0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0])

TN = ?
FP = ?
FN = ?
TP = ?

confusion_matrix = np.array([[TN, FP], [FN, TP]])
print('混淆矩阵:')
print(confusion_matrix)

# 计算精确率 Precision = TP/(TP+FP) 和召回率 Recall = TP/(TP+FN)
precision = ?
recall = ?
print(f'精确率: {precision:.3f}')
print(f'召回率: {recall:.3f}')

### 题 8.6（应用：top-k 推荐）

给定每个用户对所有商品的预测评分，找出每个用户**评分最高的前 3 个商品索引**。

提示：用 `np.argsort` 排序后取最后 3 个，或用 `np.argpartition`

In [ ]:
np.random.seed(0)
# 5 个用户对 10 个商品的预测评分
scores = np.random.rand(5, 10)
print('评分矩阵:')
print(scores.round(2))

# 每个用户的 top-3 商品
top3_per_user = ?
print('每个用户的 top-3 商品索引:')
print(top3_per_user)

### 题 8.7（终极挑战：手写 K-Means 一步迭代）⭐⭐⭐⭐

K-Means 算法的一步迭代：
1. 给定数据点 X 和 k 个聚类中心 centers
2. 把每个数据点分配到最近的中心（每个点的标签）
3. 用每个簇的均值作为新中心

**这一题综合了：距离计算、argmin、布尔索引、按 axis 求均值**

In [ ]:
np.random.seed(42)
# 30 个二维点
X = np.random.randn(30, 2)
# 3 个初始中心
centers = np.array([[0., 0.], [2., 2.], [-2., -2.]])
k = 3

# 第 1 步：计算每个点到每个中心的距离（用循环也可以）
distances = np.zeros((30, k))
for j in range(k):
    distances[:, j] = ?  # 第 j 列：所有点到中心 j 的距离

# 第 2 步：每个点分配到最近的中心
labels = ?
print('前 10 个点的标签:', labels[:10])

# 第 3 步：更新中心（每个簇的均值）
new_centers = np.zeros_like(centers)
for j in range(k):
    new_centers[j] = ?  # 第 j 个簇的均值

print('新中心:')
print(new_centers)

---

## 模块 9：广播机制（第 6 节）⭐⭐⭐

考点：广播规则、newaxis、keepdims、距离矩阵、外积

### 题 9.1（基础广播判断）

下面这些数组运算能不能广播？**先猜形状，再用代码验证**

```
(a) (3, 4) + (4,)         → ?
(b) (3, 4) + (3,)         → ?
(c) (3, 1) + (1, 4)       → ?
(d) (5, 1, 4) + (1, 6, 1) → ?
(e) (2, 3) + (3, 2)       → ?
```

In [ ]:
# 验证广播
A = np.zeros((3, 4))
v1 = np.zeros(4)
v2 = np.zeros(3)
print('(a) (3,4)+(4,):', (A + v1).shape)
# print('(b) (3,4)+(3,):', (A + v2).shape)  # 这一行先注释，看会报错吗？取消注释验证

# (c) (3,1) + (1,4)
B = np.zeros((3, 1))
C = np.zeros((1, 4))
print('(c) (3,1)+(1,4):', (B + C).shape)

# (d) (5,1,4) + (1,6,1)
D = np.zeros((5, 1, 4))
E = np.zeros((1, 6, 1))
print('(d) (5,1,4)+(1,6,1):', (D + E).shape)


### 题 9.2（标量广播）
把一个矩阵的所有元素都加 100

In [ ]:
A = np.arange(12).reshape(3, 4)
result = ?
print(result)


### 题 9.3（向量广播）
给定一个 4x3 的数据矩阵 X，每列减去该列的均值（中心化）

In [ ]:
X = np.array([[1.0, 10.0, 100.0],
              [2.0, 20.0, 200.0],
              [3.0, 30.0, 300.0],
              [4.0, 40.0, 400.0]])

X_centered = ?
print(X_centered)
print('每列均值:', X_centered.mean(axis=0))  # 应≈ [0 0 0]


### 题 9.4（newaxis 用法）

给定一维数组 a 和 b，分别完成：
1. 把 a 变成行向量（shape `(1, n)`）
2. 把 a 变成列向量（shape `(n, 1)`）
3. 用广播算 a 和 b 的外积（结果 shape `(len(a), len(b))`，元素 `[i][j] = a[i] * b[j]`）

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30])

a_row = ?       # shape (1, 4)
a_col = ?       # shape (4, 1)

print('a 行向量 shape:', a_row.shape)
print('a 列向量 shape:', a_col.shape)

# 外积
outer = ?       # shape (4, 3)
print('外积:')
print(outer)
# 期望:
# [[10 20 30]
#  [20 40 60]
#  [30 60 90]
#  [40 80 120]]


### 题 9.5（keepdims 必要性）

要把矩阵的每一行除以该行的和，让每行总和变成 1。

**先试错的写法，看报错；再用 keepdims 修正**

In [ ]:
A = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0]])

# 错误尝试（会报错或结果不对）
# wrong = A / A.sum(axis=1)
# print(wrong)   # 不对！

# 正确写法（用 keepdims）
result = ?
print(result)
print('每行的和:', result.sum(axis=1))  # [1 1]


### 题 9.6（行归一化 - L2）

把一个矩阵的每一行除以该行的 L2 范数，让每行变成单位向量。

这是 K-Means、推荐系统里的常用操作

In [ ]:
X = np.array([[3.0, 4.0],
              [6.0, 8.0],
              [1.0, 0.0]])

X_normalized = ?
print(X_normalized)
print('每行 L2 范数:', np.linalg.norm(X_normalized, axis=1))  # [1 1 1]


### 题 9.7（向量化欧氏距离矩阵）⭐⭐⭐⭐

这是题 5.10 的进阶版。给定 n 个二维点，**用广播一行代码**算所有点对之间的欧氏距离矩阵。

**思路提示**：
- `X[:, None, :]` 的 shape 是 `(n, 1, d)`
- `X[None, :, :]` 的 shape 是 `(1, n, d)`
- 相减广播得到 `(n, n, d)`
- 沿最后一维求平方和、开方

In [ ]:
X = np.array([[0.0, 0.0],
              [3.0, 4.0],
              [1.0, 1.0],
              [5.0, 5.0]])

D = ?
print(D)
# D[0][1] 应该是 5（点 (0,0) 到 (3,4) 的距离）


### 题 9.8（广播实战：批量样本与中心比较）

给定 5 个聚类中心和 100 个数据点，用广播算每个点到每个中心的距离矩阵 (100, 5)

In [ ]:
np.random.seed(0)
centers = np.random.randn(5, 2)      # 5 个中心
points = np.random.randn(100, 2)     # 100 个点

# 算 (100, 5) 距离矩阵
distances = ?
print('距离矩阵 shape:', distances.shape)

# 每个点最近的中心
labels = distances.argmin(axis=1)
print('前 10 个点的标签:', labels[:10])


### 题 9.9（找出广播错误）

下面代码会报错。
1. 解释为什么
2. 用 newaxis 修复

In [ ]:
X = np.array([[1, 2, 3],
              [4, 5, 6]])         # shape (2, 3)
y = np.array([10, 20])             # shape (2,)

# 想让 X 的每一【行】乘以 y 中对应的元素
# X[0] * 10, X[1] * 20

# 错误写法（会报错）
# result = X * y    

# 修复写法
result = ?
print(result)
# 期望:
# [[10 20 30]
#  [80 100 120]]


### 题 9.10（应用：协方差矩阵的广播实现）⭐⭐⭐⭐

用广播实现 $S = \frac{1}{n-1}(X-\bar{X})^T(X-\bar{X})$，对比 `np.cov` 验证

In [ ]:
np.random.seed(42)
X = np.random.randn(100, 3)

# 用广播实现
n = X.shape[0]
mean = ?              # 每列均值，shape (3,)
X_centered = ?        # 用广播中心化，shape (100, 3)
S_my = ?              # 协方差矩阵，shape (3, 3)

# 用 np.cov 验证
S_np = np.cov(X, rowvar=False)
print('差异:', np.abs(S_my - S_np).max())


---

## 模块 10：实用工具集合（第 7 节）⭐⭐

考点：拼接、分割、IO、unique、bincount、累计、clip、meshgrid

### 题 10.1（拼接）

给定两个矩阵，分别用 `np.vstack`、`np.hstack`、`np.concatenate` 拼接它们

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

vertical = ?      # 纵向拼接 (4, 2)
horizontal = ?    # 横向拼接 (2, 4)
concat_v = ?      # 用 concatenate 实现纵向

print('vstack:'); print(vertical)
print('hstack:'); print(horizontal)
print('concat axis=0:'); print(concat_v)


### 题 10.2（concat vs stack 区别）

两个一维数组用 stack 拼会得到什么 shape？用 concatenate 又是什么？

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

s_default = np.stack([a, b])              # shape ?
s_axis1 = np.stack([a, b], axis=1)        # shape ?
c = np.concatenate([a, b])                # shape ?

print('stack default:', s_default.shape)  # (?,?)
print('stack axis=1:', s_axis1.shape)     # (?,?)
print('concatenate:', c.shape)            # (?,)


### 题 10.3（分割）

把一个 (4, 6) 矩阵沿列方向均分成 3 份，每份 shape (4, 2)

In [ ]:
arr = np.arange(24).reshape(4, 6)
parts = ?
for i, p in enumerate(parts):
    print(f'第 {i} 份 shape:', p.shape)
    print(p)


### 题 10.4（增加/删除维度）

1. 把一维数组 shape `(5,)` 变成 `(1, 5, 1)`
2. 把 shape `(1, 5, 1)` 压缩回 `(5,)`

In [ ]:
a = np.array([1, 2, 3, 4, 5])
print('原 shape:', a.shape)

expanded = ?
print('扩展后 shape:', expanded.shape)  # (1, 5, 1)

squeezed = ?
print('压缩后 shape:', squeezed.shape)  # (5,)


### 题 10.5（tile vs repeat）

给定 `a = [1, 2, 3]`：
1. 用 tile 得到 `[1, 2, 3, 1, 2, 3, 1, 2, 3]`
2. 用 repeat 得到 `[1, 1, 1, 2, 2, 2, 3, 3, 3]`
3. 思考它们的本质区别

In [ ]:
a = np.array([1, 2, 3])

result1 = ?      # tile
result2 = ?      # repeat
print('tile:', result1)
print('repeat:', result2)


### 题 10.6（unique 统计标签）

给定一组分类标签，统计每个类别的样本数

In [ ]:
labels = np.array([0, 1, 1, 2, 0, 2, 1, 1, 0, 2, 2, 1])

classes, counts = ?
print('类别:', classes)
print('数量:', counts)
print('字典形式:', dict(zip(classes, counts)))


### 题 10.7（bincount one-hot 风格）

用 `np.bincount` 数 0-9 各出现多少次

In [ ]:
np.random.seed(0)
nums = np.random.randint(0, 10, size=100)
counts = ?
print('0-9 各出现次数:', counts)
print('总和应该是 100:', counts.sum())


### 题 10.8（cumsum 累计求和）

应统场景：算累计收益。给定每日收益率 `r`，计算累计收益

In [ ]:
r = np.array([0.01, -0.005, 0.02, -0.01, 0.015, 0.008, -0.003])

cumulative_return = ?    # 累计求和
print('累计收益:', cumulative_return)


### 题 10.9（np.clip 异常值截断）

把数组中的值限制在 [0, 100] 之间

In [ ]:
data = np.array([-50, 30, 80, 150, -10, 200, 50])
clipped = ?
print(clipped)  # [0 30 80 100 0 100 50]


### 题 10.10（np.where 找位置）

找出矩阵中所有大于 10 的元素的**位置**（行索引和列索引）

In [ ]:
A = np.array([[1, 15, 3],
              [12, 5, 20],
              [8, 25, 11]])

rows, cols = ?
print('行索引:', rows)
print('列索引:', cols)
print('对应的值:', A[rows, cols])


### 题 10.11（保存与加载）

1. 创建一个 100x10 的随机矩阵 X 和一个长度 100 的标签数组 y
2. 用 `np.savez` 保存到 'data.npz'
3. 加载并验证

In [ ]:
np.random.seed(42)
X = np.random.randn(100, 10)
y = np.random.randint(0, 3, 100)

# 保存
?

# 加载
loaded = ?
print('X shape:', loaded['X'].shape)
print('y shape:', loaded['y'].shape)
print('一致:', np.allclose(X, loaded['X']) and np.array_equal(y, loaded['y']))


### 题 10.12（meshgrid 生成网格）

生成一个 5x5 的网格点，x 和 y 都从 -2 到 2 均匀取 5 个点

In [ ]:
x = np.linspace(-2, 2, 5)
y = np.linspace(-2, 2, 5)

X, Y = ?
print('X shape:', X.shape)
print('X:'); print(X)
print('Y:'); print(Y)

# bonus: 计算每个网格点的 x²+y²
Z = X**2 + Y**2
print('Z (x²+y²):'); print(Z)


---

## 模块 11：综合大题（应用第 6-7 节）⭐⭐⭐⭐

把广播 + 实用工具串起来用

### 题 11.1（终极挑战：手写完整 K-Means）⭐⭐⭐⭐⭐

实现完整的 K-Means 算法，使用广播算距离。包含初始化、迭代、收敛判断

In [ ]:
def kmeans(X, k, max_iter=100, seed=0):
    n, d = X.shape
    np.random.seed(seed)
    
    # 1. 随机选 k 个点作为初始中心
    init_idx = np.random.choice(n, k, replace=False)
    centers = X[init_idx].copy()
    
    for iteration in range(max_iter):
        # 2. 用广播算距离矩阵 (n, k)
        distances = ?
        
        # 3. 每个点分配到最近中心
        labels = ?
        
        # 4. 更新中心：每个簇的均值
        new_centers = np.zeros_like(centers)
        for j in range(k):
            cluster_points = X[labels == j]
            if len(cluster_points) > 0:
                new_centers[j] = cluster_points.mean(axis=0)
        
        # 5. 收敛判断
        if np.allclose(centers, new_centers):
            print(f'收敛于第 {iteration+1} 步')
            break
        
        centers = new_centers
    
    return labels, centers


# 测试
np.random.seed(42)
# 生成 3 个簇的人工数据
cluster1 = np.random.randn(50, 2) + np.array([0, 0])
cluster2 = np.random.randn(50, 2) + np.array([5, 5])
cluster3 = np.random.randn(50, 2) + np.array([-5, 5])
X = np.vstack([cluster1, cluster2, cluster3])

labels, centers = kmeans(X, k=3)
print('找到的中心:')
print(centers)

# 用 unique 看每个簇的样本数
classes, counts = np.unique(labels, return_counts=True)
print('每个簇的样本数:', dict(zip(classes, counts)))


### 题 11.2（应用：手写 KNN 分类）⭐⭐⭐⭐

实现 K 近邻分类。给定训练集 (X_train, y_train) 和测试点 X_test，预测每个测试点的标签。

用广播算距离矩阵，找最近的 k 个邻居，多数投票

In [ ]:
def knn_predict(X_train, y_train, X_test, k=5):
    n_train = X_train.shape[0]
    n_test = X_test.shape[0]
    
    # 1. 用广播算距离矩阵 (n_test, n_train)
    distances = ?
    
    # 2. 每个测试点找 k 个最近邻的索引
    nearest_idx = ?    # shape (n_test, k)
    
    # 3. 多数投票
    predictions = []
    for i in range(n_test):
        neighbor_labels = y_train[nearest_idx[i]]
        # 用 bincount 数票
        votes = np.bincount(neighbor_labels)
        predictions.append(votes.argmax())
    
    return np.array(predictions)


# 测试
np.random.seed(42)
X_train = np.random.randn(100, 5)
y_train = np.random.randint(0, 3, 100)
X_test = np.random.randn(20, 5)

y_pred = knn_predict(X_train, y_train, X_test, k=5)
print('测试预测:', y_pred)


### 题 11.3（应用：批量计算余弦相似度矩阵）⭐⭐⭐

推荐系统场景：计算用户两两之间的余弦相似度矩阵

$\text{sim}(u_i, u_j) = \frac{u_i \cdot u_j}{\|u_i\| \|u_j\|}$

In [ ]:
np.random.seed(0)
# 10 个用户的嵌入向量（每人 5 维）
users = np.random.randn(10, 5)

# 1. 先归一化每行（行 L2 范数 = 1）
users_norm = ?

# 2. 用矩阵乘法直接得到相似度矩阵
sim_matrix = ?

print('相似度矩阵 shape:', sim_matrix.shape)
print('对角线（每个用户和自己）:', np.diag(sim_matrix))  # 应该全是 1


### 题 11.4（综合：数据预处理流水线）

模拟一个真实数据预处理流程：
1. 用 random 生成 (1000, 5) 数据，加入 5% 的 NaN
2. 用列均值填补 NaN
3. Z-score 标准化
4. 用 clip 截断 ±3 倍标准差外的异常值
5. 保存成 npz

In [ ]:
np.random.seed(42)
n, d = 1000, 5
X = np.random.randn(n, d)

# 加入 5% NaN
mask = np.random.rand(n, d) < 0.05
X[mask] = np.nan

# Step 1: 用列均值填补 NaN
col_means = ?     # 用 nanmean
nan_positions = np.isnan(X)
# 注意：广播+布尔索引
for j in range(d):
    X[np.isnan(X[:, j]), j] = col_means[j]
# 验证
print('剩余 NaN:', np.isnan(X).sum())

# Step 2: Z-score 标准化（用广播）
X_std = ?

# Step 3: 截断到 ±3
X_clipped = ?

# Step 4: 保存
?
print('保存完成')

# 验证可加载
loaded = np.load('preprocessed.npz')
print('加载验证 shape:', loaded['X'].shape)


---

## 🎉 完成检查清单（覆盖第 1-7 节）

### 概念理解
- [ ] 能说出 NumPy 数组与 Python list 的 3 个区别
- [ ] 能解释 `*` 和 `@` 的不同含义
- [ ] 能解释 `(3,)`、`(1,3)`、`(3,1)` 的区别
- [ ] 能说出 `axis=0` 是「消掉哪个维度」
- [ ] 能说出切片返回的是视图还是副本
- [ ] 能口述广播的 4 条规则
- [ ] 能解释 `keepdims` 的作用

### 操作熟练
- [ ] 不查文档能创建各种数组
- [ ] 能熟练写多条件布尔筛选
- [ ] 能用一行代码实现 sigmoid、softmax、ReLU、MSE
- [ ] 能用矩阵公式实现线性回归
- [ ] 能用广播算距离矩阵
- [ ] 能用 newaxis 扩展维度

### 应用熟练
- [ ] 能完整手写 K-Means
- [ ] 能完整手写 KNN
- [ ] 能完整手写线性回归
- [ ] 能用 NumPy 做完整数据预处理流水线

---

## 📌 接下来

完成后告诉 Claude「全部做完了」，他会：
1. 提供逐题答案
2. 重点讲解你卡住的题
3. 进入 **Pandas** 学习
